name: "pre-release"

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
      - name: "Setup Python"
        uses: actions/setup-python@v4
        with:
          python-vesrion: "3.10"
      - name: "Dependencies"
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
          pip install tox tox-gh-actions
      - name: "Test with tox"
        run: tox
      - name: "Build"
        run: python -m build
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            ./dist/*.whl
            ./dist/*.gz
