name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
      - name: "Setup Python"
        uses: actions/setup-python@v4
        with:
          python-vesrion: "3.10"
      - name: "Dependencies"
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
          pip install tox tox-gh-actions
      - name: "Test with tox"
        run: tox
      - name: "Build"
        run: python -m build

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ./dist/*.whl
            ./dist/*.gz

      - name: "Publish package distributions to PyPI"
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

